# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.255.1', netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
    ]
  },
  :centralRouter => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.255.2', netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
      {ip: '192.168.0.1',   netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
      {ip: '192.168.0.33',  netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
      {ip: '192.168.0.65',  netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
      {ip: '192.168.2.1',   netmask: "255.255.255.192", virtualbox__intnet: "office1-dev"},
      {ip: '192.168.1.1',   netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
    ]
  },
  :centralServer => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.0.2', netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
    ]
  },

  # Office1
  :office1Router => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.2.65',  netmask: "255.255.255.192", virtualbox__intnet: "office1-test"},
      {ip: '192.168.2.129', netmask: "255.255.255.192", virtualbox__intnet: "office1-mgr"},
      {ip: '192.168.2.193', netmask: "255.255.255.192", virtualbox__intnet: "office1-hw"},
      {ip: '192.168.2.2',   netmask: "255.255.255.192", virtualbox__intnet: "office1-dev"},
    ]
  },
  :office1Server => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.2.66', netmask: "255.255.255.192", virtualbox__intnet: "office1-test"},
    ]
  },

  # Office2
  :office2Router => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.1.129', netmask: "255.255.255.192", virtualbox__intnet: "office2-test"},
      {ip: '192.168.1.193', netmask: "255.255.255.192", virtualbox__intnet: "office2-hw"},
      {ip: '192.168.1.2',   netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
    ]
  },
  :office2Server => {
    :box_name => "ubuntu24-noble",
    :net => [
      {ip: '192.168.1.130', netmask: "255.255.255.192", virtualbox__intnet: "office2-test"},
    ]
  },
}

Vagrant.configure("2") do |config|
  # Парольная аутентификация
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", **ipconf
      end

		box.vm.provision "shell", inline: <<-SHELL
		  mkdir -p ~root/.ssh
		  cp ~vagrant/.ssh/authorized_keys ~root/.ssh/
		  sed -i 's/#\\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
		  sed -i 's/#\\?PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
		  systemctl restart ssh
		SHELL

      case boxname.to_s
      when "inetRouter"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          sysctl -w net.ipv4.ip_forward=1
          ip route add default via 10.0.2.2 dev enp0s3 2>/dev/null || true
		  iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o enp0s3 -j MASQUERADE
        SHELL

	  when "centralRouter"
	    box.vm.provision "shell", run: "always", inline: <<-SHELL
		  sysctl -w net.ipv4.ip_forward=1
		  ip route del default via 10.0.2.2 dev enp0s3 2>/dev/null || true
		  ip route add default via 192.168.255.1
		  # Маршруты к другим сетям
		  ip route add 192.168.2.0/24 via 192.168.2.2
		  ip route add 192.168.1.0/24 via 192.168.1.2
		  iptables -t nat -A POSTROUTING -s 192.168.0.0/16 -o enp0s8 -j MASQUERADE
	    SHELL

	  when "office1Router"
	    box.vm.provision "shell", run: "always", inline: <<-SHELL
		  sysctl -w net.ipv4.ip_forward=1
		  ip route del default via 10.0.2.2 dev enp0s3 2>/dev/null || true
		  ip route add default via 192.168.2.1
		  # Маршруты к другим сетям
		  ip route add 192.168.0.0/24 via 192.168.2.1
		  ip route add 192.168.1.0/24 via 192.168.2.1
	    SHELL

	  when "office2Router"
	    box.vm.provision "shell", run: "always", inline: <<-SHELL
		  sysctl -w net.ipv4.ip_forward=1
		  ip route del default via 10.0.2.2 dev enp0s3 2>/dev/null || true
		  ip route add default via 192.168.1.1
		  # Маршруты к другим сетям
		  ip route add 192.168.0.0/24 via 192.168.1.1
		  ip route add 192.168.2.0/24 via 192.168.1.1
	    SHELL

      when "centralServer"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          ip route del default via 10.0.2.2 dev enp0s3 2>/dev/null || true
          ip route add default via 192.168.0.1
        SHELL

      when "office1Server"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          ip route del default via 10.0.2.2 dev enp0s3 2>/dev/null || true
          ip route add default via 192.168.2.65
        SHELL

      when "office2Server"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          ip route del default via 10.0.2.2 dev enp0s3 2>/dev/null || true
          ip route add default via 192.168.1.129
        SHELL
      end
    end
  end
end