[frontend]
front ansible_host=192.168.50.10

[backend]
back1 ansible_host=192.168.50.11 db_role=master server_id=1
back2 ansible_host=192.168.50.12 db_role=slave server_id=2

[monitoring]
monitor ansible_host=192.168.50.20

[logging]
logger ansible_host=192.168.50.21

[all:vars]
ansible_user=vagrant
ansible_become=yes