Vagrant.configure("2") do |config|
  config.vm.box = "myubuntu"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "backup_server" do |server|
    server.vm.hostname = "backup-server"
    server.vm.provider "hyperv" do |hv|
      hv.memory = 1024
      hv.cpus = 1
      hv.enable_virtualization_extensions = true
      hv.enable_enhanced_session_mode = false
      hv.linked_clone = true
    end
    server.vm.provision "shell", run: "always", inline: <<-SHELL
      echo "=== $(hostname) ==="
      ip -4 addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1
    SHELL
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.provider "hyperv" do |hv|
      hv.memory = 1024
      hv.cpus = 1
      hv.enable_virtualization_extensions = true
      hv.enable_enhanced_session_mode = false
      hv.linked_clone = true
    end
    client.vm.provision "shell", run: "always", inline: <<-SHELL
      echo "=== $(hostname) ==="
      ip -4 addr show eth0 | awk '/inet / {print $2}' | cut -d/ -f1
    SHELL
  end
end